mysite/urls.py
from django.contrib import admin
from django.urls import path, include


"""
Temporary debug function in production environment.
Comment out this part if you don't use debug function
"""
from todolist import views
handler500 = views.my_customized_server_error
# End of debug function

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todolist/', include('todolist.urls')),
    path('accounts/', include('allauth.urls')), 
]

todolist/urls.py
from django.urls import path
from . import views


# 1つのプロジェクトに複数のアプリケーションがあって，アプリで同じURLがある場合に指定する
app_name = 'todolist'


urlpatterns = [
    path('index/',                                      views.index,                        name='index'),
    path('home/',                                       views.HomeView.as_view(),           name='home'),
    path('tasks/',                                      views.TodoListView.as_view(),       name='todomodel_list'),
    path('tasks/<int:pk>/',                             views.TodoDetailView.as_view(),     name='todomodel_detail'), 
    path('tasks/new/',                                  views.TodoCreateView.as_view(),     name='todomodel_new'), 
    path('tasks/<int:pk>/edit/',                        views.TodoUpdateView.as_view(),     name='todomodel_edit'), 
    path('tasks/<int:pk>/confirm_delete/',              views.TodoDeleteView.as_view(),     name='todomodel_confirm_delete'), 
    
    path('workdates/',                                  views.WorkDateListView.as_view(),   name='workdatemodel_list'), 
    path('workdates/new/',                              views.WorkDateCreateView.as_view(), name='workdatemodel_new'), 
    path('workdates/<slug:slug>/',                      views.WorkDateDetailView.as_view(), name='workdatemodel_detail'), 
    path('workdates/<slug:slug>/edit/',                 views.WorkDateUpdateView.as_view(), name='workdatemodel_edit'), 
    path('workdates/<slug:slug>/confirm-delete/',       views.WorkDateDeleteView.as_view(), name='workdatemodel_delete'), 
    
    path('workdates/workmode/<slug:slug>/<int:order>/', views.WorkModeView.as_view(),       name='workmode'), 
    path('workdates/workmode/<slug:slug>/drop/',        views.WorkModeDropView.as_view(),   name='workmode_drop'), 
    
    path('analysis/',                                   views.AnalysisView.as_view(),       name='analysis'),
    ]

todolist/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
import math


# class WorkModeModel(models.Model):
#     # シングルトン実装して作業モードの実行状態を監視する？
#
#     class Meta:
#         verbose_name = '作業モードモデル'
#
#     workdate = models.OneToOneField()
#     is_running = models.BooleanField()
#     has_instance = False
#
#
#     def __str__(self):
#         return self.workdate
#
#     def __new__(self):
#         if self.has_instance:
#             raise Exception('インスタンスは一つまで') 
#         return super().__new__()


class WorkDateModel(models.Model):
    
    class Meta:
        verbose_name = '作業モデル'
        verbose_name_plural = '作業リスト'
        
        constraints = [
            models.UniqueConstraint(
                fields = ['work_date', 'user'], 
                name   = 'unique_workdate_in_user'
            ), 
            models.UniqueConstraint(
                fields = ['slug', 'user'], 
                name   = 'unique_slug_in_user'
            ),
        ]
    
    work_date                       = models.DateField(verbose_name='作業日', null=False, blank=False)
    is_finished                     = models.BooleanField(verbose_name='終了したかどうか', default=False)
    average_plan_excution_time_rate = models.FloatField(verbose_name='平均計画実行時間割合', default=0, blank=True)
    todo_achievement_rate_in_a_day  = models.FloatField(verbose_name='1日の進捗率', default=0, blank=True)
    slug                            = models.SlugField(verbose_name='スラッグ', blank=True)
    create_at                       = models.DateTimeField(verbose_name='登録日時')
    update_at                       = models.DateTimeField(verbose_name='更新日時')
    user                            = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='ユーザー名', null=False, blank=False, related_name='work_date_models')
    
    
    def __str__(self):
        return str(self.work_date)
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.create_at = timezone.now()
            self.slug = str(self.work_date)
        self.update_at = timezone.now()
        
        if self.is_finished:
            self.set_average_plan_excution_time_rate()
            self.set_todo_achievement_rate_in_a_day()
        else:
            self.average_plan_excution_time_rate = 0
            self.todo_achievement_rate_in_a_day = 0
        
        return super().save(*args, **kwargs)
    
    def delete(self, using=None, keep_parents=False):
        # Adminで一括削除した場合はこのメソッドは呼ばれない。
        todomodel_list = self.todomodel_list.all()
        if len(todomodel_list):
            for todomodel in todomodel_list:
                todomodel.order = 0
                todomodel.save()
        return super().delete(using=using, keep_parents=keep_parents)
    
    def set_average_plan_excution_time_rate(self):
        sum_ptr = 0
        todomodel_list = self.todomodel_list.all()
        for todomodel in todomodel_list:
            sum_ptr += todomodel.plan_excution_time_rate
        self.average_plan_excution_time_rate = "{:.2f}".format(sum_ptr / len(todomodel_list))
    
    def set_todo_achievement_rate_in_a_day(self):
        total_expected_time = 0
        total_todo_achievement_time = 0
        todomodel_list = self.todomodel_list.all()
        for todomodel in todomodel_list:
            total_expected_time += todomodel.expected_time 
            total_todo_achievement_time += todomodel.expected_time * (todomodel.achievement_rate / 100)
        try:
            self.todo_achievement_rate_in_a_day = "{:.2f}".format((total_todo_achievement_time / total_expected_time) * 100)
        except ZeroDivisionError:
            self.todo_achievement_rate_in_a_day = 0


class TodoModel(models.Model):
    
    class Meta:
        verbose_name = 'ToDoモデル'
        verbose_name_plural = 'ToDoリスト'
    
    title                   = models.CharField(verbose_name='ToDo', max_length=100, null=False)
    limit_time              = models.DateTimeField(verbose_name='期限')     # デフォルトのフォーマットはYYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]
    expected_time           = models.PositiveSmallIntegerField(verbose_name='目標時間（秒）', default=0, blank=True)
    work_date_model         = models.ForeignKey(WorkDateModel, on_delete=models.SET_NULL, verbose_name='作業日', null=True, blank=True, related_name='todomodel_list')
    order                   = models.PositiveSmallIntegerField(verbose_name='作業順', default=0, null=False)
    actual_time             = models.PositiveSmallIntegerField(verbose_name='実際の時間（秒）', default=0)
    plan_excution_time_rate = models.FloatField(verbose_name='計画実行時間割合', default=0, blank=True)
    achievement_rate        = models.IntegerField(verbose_name='ToDo達成割合（%）', default=0)
    create_at               = models.DateTimeField(verbose_name='登録日時')
    update_at               = models.DateTimeField(verbose_name='更新日時')
    user                    = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='ユーザー名', null=False, blank=False, related_name='todomodel_list')
    
    
    field_names_min_to_sec = {'expected_time', 'actual_time'}
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.create_at = timezone.now()
        self.update_at = timezone.now()
        
        if self.work_date_model:
            self.work_date_model.update_at = timezone.now()
        
        if self.achievement_rate != 0:
            self.set_plan_excution_time_rate()
        else:
            self.plan_excution_time_rate = 0
        return super().save(*args, **kwargs)
    
    def delete(self, using=None, keep_parents=False):
        if self.work_date_model is not None:
            self.work_date_model.update_at = timezone.now()
            
            # 作業モデルのToDo実行順序を修正する
            todomodel_list = self.work_date_model.todomodel_list.order_by('order').all()
            for todomodel in todomodel_list[self.order:]:
                todomodel.order -= 1
                todomodel.save()
        return super().delete(using=using, keep_parents=keep_parents)
    
    def apply_registered_form(self, order, form, work_date_obj):
        """
        FormSetでクライアント側で動的に作成したフォームをDBに保存する際に利用する。
        動的に作成したFormSetのフォームはインスタンスがFormと結びついておらず、（form.instanceに値が入っていない）
        form.save()してもフォーム入力内容がDBに保存されないため。
        """
        # 基本情報の反映
        self.work_date_model = work_date_obj
        self.order = order
        
        # フォーム入力内容の反映
        cleaned_data = form.cleaned_data
        for key, value in cleaned_data.items():
            if key in ('title', 'id'):
                continue
            elif key in self.field_names_min_to_sec:
                self.convert_form_value_min_to_sec(key, value)
            else:
                setattr(self, key, value)
    
    def apply_deleted_form(self):
        self.work_date_model = None
        self.order = 0
    
    def expected_time_min(self):
        return str(self.expected_time // 60)
    
    def actual_time_min(self):
        m = str(self.actual_time // 60)
        s = str(self.actual_time % 60).zfill(2)
        return m, s
    
    def convert_form_values_min_to_sec(self, form, field_names=field_names_min_to_sec):
        for field_name in form.fields.keys():
            if field_name not in field_names:
                continue
            
            value = form.cleaned_data[field_name] or 0
            instance_exists = True if self.__class__.objects.filter(pk=self.id).first() else False
            
            self.convert_form_value_min_to_sec(field_name, value, instance_exists)
    
    def convert_form_value_min_to_sec(self, field_name, cleaned_val, instance_exists=True):
        def should_update(field_name, cleaned_val):
            # TODO : クエリ発行しないようにするために、新しくタスクを作成する場合は、フォームにチェック入れる等して、
            # DBを参照せずに、formの値から判断するように改善する。
            if not(instance_exists):
                return True
            db_value   = getattr(self, field_name, 0)
            form_value = cleaned_val
            db_value = math.ceil(db_value / 60)
            return db_value != form_value
        
        if should_update(field_name, cleaned_val):
            value = cleaned_val * 60
            setattr(self, field_name, value)
    
    def set_plan_excution_time_rate(self):
        try:
            if self.achievement_rate == 100:
                if self.expected_time is not None:
                    self.plan_excution_time_rate = "{:.2f}".format(self.actual_time / self.expected_time)
            elif self.achievement_rate == 0:
                self.plan_excution_time_rate = 0
            else:
                self.plan_excution_time_rate = "{:.2f}".format(self.actual_time / (self.expected_time * (self.achievement_rate / 100)))
        except ZeroDivisionError:
            self.plan_excution_time_rate = 0
    
    @classmethod
    def evaluate_total_todos(cls, user):
        """これまでの実行した全てのToDoをDBから取得し、平均計画実行時間割合とToDo達成割合を計算して返す"""
        queryset = cls.objects.filter(user=user).exclude(achievement_rate=0).all()
        num = len(queryset)
        total_plan_excution_time_rate = 0
        total_expected_time = 0
        total_todo_achievement_time = 0
        
        for obj in queryset:
            total_plan_excution_time_rate += obj.plan_excution_time_rate
            total_expected_time += obj.expected_time
            total_todo_achievement_time += obj.expected_time * (obj.achievement_rate / 100)
        
        average_plan_excution_time_rate = "{:.2f}".format(total_plan_excution_time_rate / num)
        whole_todo_achievement_rate = "{:.2f}".format((total_todo_achievement_time / total_expected_time) * 100)

todolist/templates/todolist/analysis.html
{% extends 'todolist/base.html' %}
{% load static %}

{% block head %}
<title>評価結果</title>
<link rel="stylesheet" type="text/css" href="{% static 'todolist/css/todolist_style.css' %}"/>
{% endblock head %}

{% block content %}
    <h2>評価結果</h2>

{% endblock content %}

todolist/templates/todolist/base.html
{% load static %}
{% load todolist_extras %}

<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="description" content="作業効率を可視化することで、日々の作業に対するモチベーションと作業効率を高めていけるタスク管理型のWebアプリケーションです。">
  <meta property="og:url" content="{% url 'todolist:index' %}">
  <meta property="og:type" content="website">
  <meta property="og:title" content="タスク管理アプリ">
  <meta property="og:description" content="作業効率を可視化することで、日々の作業に対するモチベーションと作業効率を高めていけるタスク管理型のWebアプリケーションです。">
  <meta property="og:image" content="{% static 'todolist/img/icon.png' %}">

  <link rel="icon" type="image/png" href="{% static 'todolist/img/icon.png' %}"/>
  <!-- <link rel="stylesheet" type="text/css" href="https://unpkg.com/ress/dist/ress.min.css"/> -->
  <link rel="stylesheet" type="text/css" href="{% static 'todolist/css/base.css' %}"/>

  {% block index_head %}
  {% if not view|is_cud_view %}
  <link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.13.1/themes/smoothness/jquery-ui.css"/>
  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js" integrity="sha256-eTyxS0rkjpLEo16uXTS0uVCS4815lc40K2iVpWDvdSY=" crossorigin="anonymous"></script>
  {{ workmode_info|json_script:"workmode_info" }}
  <script type="text/javascript">
    $(function() {
        $('body').attr('onload', function(){
            window.name = "parent-window";
        });

        var workmode_info = document.getElementById('workmode_info').textContent;
        workmode_info = JSON.parse(workmode_info);

        // 作業モード遷移の条件を満たしている場合
        if (workmode_info.status === 'available') {
            // 作業モード遷移処理
            $('#workmode-form').attr({
                'action' : workmode_info.url, 
                'target' : 'subwindow', 
            });
            $('#workmode-form button').click(function(){
                window.open(workmode_info.url, "subwindow", "width=400, height=180, top=680, left=1248");
            });
        
        // 作業モード遷移の条件を満たしていない場合
        } else {
            let dlg = $('#workmode-dialog')
            let buttons = new Object();
            for (let button_info of workmode_info.dialog_data.buttons){
                buttons[button_info.name] = function(){
                    if (button_info.url === null) {
                        dlg.dialog('close');
                    } else {
                        window.location.href = button_info.url;
                    }
                }
            }
            dlg.dialog({
                modal: true, 
                autoOpen: false, 
                title: '警告', 
                buttons: buttons,
            });

            // ダイアログ表示処理
            $('#workmode-form button').click(function(){
                dlg.dialog('open');
            });

            if (workmode_info.status === "no_today_model") {
                $('#today-model').attr("href", "#");
                $('#today-model').click(function(){
                    dlg.dialog('open');
                });
            }
        }
    });
  </script>
  {% endif %}
  {% endblock index_head %}
  {% block head %}
  {% endblock head %}
</head>
<body>
  <div class="container">
    <header class="page-header">
      <div class="wrapper">
        <a class="header-title" href="{% url 'todolist:index' %}">
          <img class="logo" src="{% static 'todolist/img/icon.png' %}" alt="アイコン">
          <h1>タスク管理アプリ</h1>
        </a>
        <div class="account-info">
          {% if user.is_authenticated %}
            {% block top_page_user_content %}
            <ul class="user-nav">
              <li><a href="#">{{ user.username }}</a></li>
              <li><a href="{% url 'account_logout' %}">ログアウト</a></li>
            </ul>
            {% endblock top_page_user_content %}
          {% else %}
            <a class="button" href="{% url 'account_login' %}">ログイン</a>
            <a class="account-registration button" href="{% url 'account_signup' %}">会員登録</a>
          {% endif %}
        </div>
      </div>
    </header>
    {% block index_content %}
      <div class="main all-content wrapper">
        <main class="main-content">
          {% block content %}
          {% endblock content %}
        </main>
        <aside class="aside-content">
            <div class="side-item-fixed">
                <h3 class="sub-title">メニュー</h3>
                <ul class="sub-menu">
                    <li><a href="{% url 'todolist:home' %}">ホーム</a></li>
                    <li><a href="{% url 'todolist:todomodel_list' %}">ToDo一覧</a></li>
                    <li><a href="{% url 'todolist:workdatemodel_list' %}">作業データ一覧</a></li>
                    <li><a href="#">評価</a></li>
                </ul>
                {% if not view|is_cud_view %}
                <div class="a-block-center">
                  <form id="workmode-form" class="workmode" method="get">
                      <button class="workmode-butto button" type="button">本日の作業開始</button>
                  </form>
                </div>
                {% endif %}
            </div>
        </aside>
      </div>
    {% endblock index_content %}
    <footer>
      <p><small>Copyrights &copy; 2022 Totaro All Rights Reserved.</small></p>
    </footer>
  </div>
  <div id="workmode-dialog" class="dialog">
    {% for message in workmode_info.dialog_data.messages %}
    <p>{{ message }}</p>
    {% endfor %}
  </div>
</body>
</html>

todolist/templates/todolist/home.html
{% extends 'todolist/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'todolist/css/todolist_style.css' %}"/>
<title>Home</title>
{% endblock head %}

{% block content %}
<h2>Home</h2>
<div class="">
    <p><a href="{% url 'todolist:todomodel_list' %}">ToDoリスト一覧</a></p>
    <p><a href="{% url 'todolist:workdatemodel_list' %}">作業データ一覧</a></p>
    <p><a id="today-model" href="{% url 'todolist:workdatemodel_detail' slug='today' %}">今日の作業</a></p>
    <p><a href="#">作業結果分析</a></p>
</div>
{% endblock content %}

todolist/templates/todolist/todomodel_detail.html
{% extends 'todolist/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'todolist/css/todolist_style.css' %}"/>
<title>ToDoリスト/{{ object.title }}</title>
{% endblock head %}

{% block content %}
<h2>ToDoの詳細</h2>
<table>
    <thead>
        <tr>
            <th>ToDo</th>
            <th>期限</th>
            <th>作業予定日</th>
            <th>ToDo実行状況</th>
            <th>目標時間</th>
            <th>実際の時間</th>
            <th>計画実行時間割合</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ object.title }}</td>
            <td>{{ object.limit_time }}</td>
            <td>
                {% if object.work_date_model is not None %}
                <a href="{% url 'todolist:workdatemodel_detail' slug=object.work_date_model.slug %}">{{ object.work_date_model.work_date }}</a>
                {% endif %}
            </td>
            <td>{{ object.achievement_rate }} %</td>
            <td>{{ object.expected_time_min }}分</td>
            <td>{{ object.actual_time_min.0 }}分{{ object.actual_time_min.1 }}秒</td>
            <td>{{ object.plan_excution_time_rate }}</td>
        </tr>
    </tbody>
</table>
<table>
    <tr>
        <td><form action="{% url 'todolist:todomodel_edit' object.id %}" method="get"><button type="submit">編集</button></form></td>
        <td><form action="{% url 'todolist:todomodel_confirm_delete' object.id %}" method="get"><button type="submit">削除</button></form></td>
    </tr>
</table>
{% endblock content %}

todolist/templates/todolist/todomodel_list.html
{% extends 'todolist/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'todolist/css/todolist_style.css' %}"/>
<title>ToDoリスト</title>
{% endblock head %}

{% block content %}
    <h2>ToDoの一覧</h2>

    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'todolist success' %}
                <p>{{ message }}</p>
            {% endif %}
        {% endfor %}
    {% endif %}
    
    <td><form action="{% url 'todolist:todomodel_new' %}" method="get"><button type="submit">ToDoを追加</button></form></td>
    <table>
        <thead>
            <tr>
                <th>ToDo</th>
                <th>期限</th>
                <th>作業予定日</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <td><a href="{{ object.id }}/">{{ object.title }}</a></td>
                <td>{{ object.limit_time }}</td>
                <td>{{ object.work_date_model.work_date }}</td>
                {% if not object.is_completed %}
                <td><form action="{% url 'todolist:todomodel_confirm_delete' object.id %}" method="get"><button type="submit">削除</button></form></td>
                <td><form action="{% url 'todolist:todomodel_edit' pk=object.id %}" method="get"><button type="submit">編集</button></form></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a class="page-link text-primary d-inline-block" href="../{{ page_obj.previous_page_number }}/"><<</a></li>
            {% else %}
                <li class="disabled"><div class="page-link text-secondary d-inline-block disabled" href="#"><<</div></li>
            {% endif %}

            {% for page_num in page_obj.paginator.page_range %}
                {% if page_num %}
                    {% if page_num == pages.number %}
                        <li class="disabled"><div class="page-link text-secondary d-inline-block disabled" href="#">{{ page_num }}</div></li>
                    {% else %}
                        <li><a class="page-link text-primary d-inline-block" href="../{{ page_num }}/">{{ page_num }}</a></li>
                    {% endif %}
                {% else %}
                    <li class="disabled"><a class="page-link text-secondary d-inline-block text-muted" href="#">・・・</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li><a class="page-link text-primary d-inline-block" href="../{{ page_obj.next_page_number }}/">>></a></li>
            {% else %}
                <li class="disabled"><div class="page-link text-secondary d-inline-block disabled" href="#">>></div></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
{% endblock content %}

todolist/templates/todolist/workdatemodel_confirm_delete.html
{% extends 'todolist/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'todolist/css/todolist_style.css' %}"/>
<title>作業データの削除 {{ workdatemodel.work_date }}</title>
{% endblock head %}

{% block content %}
    <h2>作業データの削除</h2>
    <p>以下の作業データを削除しますか？</p>
    <p>※ToDoの内容自体は削除されません。</p>
    {% if object.is_finished %}
    <p>※この作業データは実行済みのデータです。分析結果に影響します。</p>
    {% endif %}

    <table>
        <tr>
            <td><form method="post">{% csrf_token %}<button type="submit">削除</button></form></td> 
            <td><form action="{% url 'todolist:workdatemodel_list' %}" method="get"><button type="submit">キャンセル</button></form></td>
        </tr>
    </table>

    <table>
        <tr><th>作業予定日</th><td></td></tr>
        <tr><th></th><td>{{ workdatemodel.work_date }}</td></tr>

        <tr><th>平均計画実行時間割合</th><td></td></tr>
        <tr><th></th><td>{{ workdatemodel.average_plan_excution_time_rate }}</td></tr>

        <tr><th>1日の進捗率</th><td></td></tr>
        <tr><th></th><td>{{ workdatemodel.todo_achievement_rate_in_a_day }} %</td></tr>
        
        <tr><th>作業内容</th><td></td></tr>
        {% for todomodel in todomodel_list %}
            <div>
            <tr>
                <th>{{ todomodel.order }}</th><td></td>
            </tr>
            <tr>
                <th>ToDo</th><td><a href="{% url 'todolist:todomodel_detail' todomodel.id %}">{{ todomodel.title }}</a></td>
            </tr>
            <tr>
                <th>期限</th><td>{{ todomodel.limit_time }}</td>
            </tr>
            <tr>
                <th>目標時間</th><td>{{ todomodel.expected_time_min }}分</td>
            </tr>
            <tr>
                <th>実際の時間</th><td>{{ todomodel.actual_time_min.0 }}分{{ todomodel.actual_time_min.1 }}秒</td>
            </tr>
            <tr>
                <th>計画実行時間割合</th><td>{{ todomodel.plan_excution_time_rate }}</td>
            </tr>
            <tr>
                <th>ToDo達成割合</th><td>{{ todomodel.achievement_rate }}</td>
            </tr>
            </div>
        {% empty %}
            <tr><th></th><td>ToDoが登録されていません。</td></tr>
        {% endfor %}
    </table>

{% endblock content %}

todolist/templates/todolist/workdatemodel_detail.html
{% extends 'todolist/base.html' %}
{% load static %}
{% load todolist_extras %}

{% block head %}
<title>作業データの詳細 {{ workdatemodel.work_date }}</title>
<link rel="stylesheet" type="text/css" href="{% static 'todolist/css/todolist_style.css' %}"/>
{% endblock head %}

{% block content %}
    <h2>作業データの詳細</h2>
    
    <table>
        <tr><th>作業日</th><td></td></tr>
        <tr><th></th><td>{{ workdatemodel.work_date }}</td></tr>

        <tr><th>平均計画実行時間割合</th><td></td></tr>
        <tr><th></th><td>{{ workdatemodel.average_plan_excution_time_rate }}</td></tr>

        <tr><th>1日の進捗率</th><td></td></tr>
        <tr><th></th><td>{{ workdatemodel.todo_achievement_rate_in_a_day }}</td></tr>
        
        <tr><th>作業内容</th><td></td></tr>
        {% for todomodel in todomodel_list %}
            <div>
            <tr>
                <th>{{ todomodel.order }}</th><td></td>
            </tr>
            <tr>
                <th>ToDo</th><td><a href="{% url 'todolist:todomodel_detail' pk=todomodel.id %}">{{ todomodel.title }}</a></td>
            </tr>
            <tr>
                <th>期限</th><td>{{ todomodel.limit_time }}</td>
            </tr>
            <tr>
                <th>目標時間</th><td>{{ todomodel.expected_time_min }}分</td>
            </tr>
            <tr>
                <th>実際の時間</th><td>{{ todomodel.actual_time_min.0 }}分 {{ todomodel.actual_time_min.1 }}秒</td>
            </tr>
            <tr>
                <th>計画実行時間割合</th><td>{{ todomodel.plan_excution_time_rate }}</td>
            </tr>
            <tr>
                <th>ToDo達成割合</th><td>{{ todomodel.achievement_rate }}%</td>
            </tr>
            </div>
        {% empty %}
            <tr><th></th><td>ToDoが登録されていません。</td></tr>
        {% endfor %}
    </table>
    <table>
        <tr>
            <td>
                <form action="{% url 'todolist:workdatemodel_delete' slug=workdatemodel.slug %}" method="get"><button type="submit">削除</button></form>
            </td>
            <td>
                <form action="{% url 'todolist:workdatemodel_edit' slug=workdatemodel.slug %}" method="get"><button type="submit">編集</button></form>
            </td>
        </tr>
    </table>
{% endblock content %}